#!/usr/bin/env python3
"""
inject_blog_entry.py — Insert a blog_snippet.html into the MORELLOSIMS blog.

Reads blog_snippet.html (generated by generate_blog_entry.py) and injects:
  - Pick cards wrapped in <details class="slate-day"> into the blog
  - Table rows into the picks tracker table

Supports both:
  - Fresh injection: date doesn't exist in blog → creates new <details> block
  - Append mode: date already exists → adds only NEW picks to existing block

Usage:
  python scripts/inject_blog_entry.py <blog_snippet.html> <morellosims_index.html>
"""

import re
import sys
from datetime import datetime


# Day-of-week abbreviations
DAYS = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]


def _extract_pick_cards(html_block):
    """Extract individual pick cards from an HTML block.

    Returns list of (matchup, card_html) tuples.
    """
    cards = []
    for m in re.finditer(
        r'(<div class="pick-card"[^>]*data-matchup="([^"]+)"[^>]*>.*?</div>\s*</div>)',
        html_block,
        re.DOTALL,
    ):
        cards.append((m.group(2), m.group(1)))
    return cards


def _extract_table_rows(table_html, short_date):
    """Extract individual table rows (skip the date header row).

    Returns list of (matchup, row_html) tuples.
    """
    rows = []
    for m in re.finditer(
        r'(<tr style="border-bottom.*?</tr>)',
        table_html,
        re.DOTALL,
    ):
        row = m.group(1)
        matchup_m = re.search(r'color:#e0e0e0;">(.*?)</td>', row)
        if matchup_m:
            rows.append((matchup_m.group(1), row))
    return rows


def _existing_matchups(html, short_date, day_name):
    """Find matchups already present in the blog for a given date.

    Scans the <details> block for that date and extracts data-matchup values.
    """
    matchups = set()

    # Find the details block for this date
    pattern = re.compile(
        rf'<details class="slate-day"[^>]*>\s*<summary>.*?'
        rf'{re.escape(short_date)}.*?</summary>\s*'
        rf'<div class="slate-day-body">(.*?)</div>\s*</details>',
        re.DOTALL,
    )
    block = pattern.search(html)
    if block:
        body = block.group(1)
        for m in re.finditer(r'data-matchup="([^"]+)"', body):
            matchups.add(m.group(1))

    return matchups


def _parse_snippet(snippet):
    """Parse the blog snippet into cards HTML, table HTML, and metadata."""
    table_marker = "<!-- ═══ TABLE ROWS (insert before </tbody>) ═══ -->"
    cards_marker = "<!-- ═══ PICK CARDS (insert before picks table) ═══ -->"

    cards_html = ""
    table_html = ""

    if table_marker in snippet:
        parts = snippet.split(table_marker)
        cards_section = parts[0]
        table_html = parts[1].strip()
    else:
        cards_section = snippet

    # Extract just the pick card divs (remove comment headers)
    cards_html = cards_section.replace(cards_marker, "")
    cards_html = re.sub(r'<!-- Blog snippet for .+? -->\n', '', cards_html)
    cards_html = re.sub(r'<!-- \d+ picks?, \d+ \$PP risked -->\n', '', cards_html)
    cards_html = cards_html.strip()

    # Remove the standalone slate header div (used in details summary instead)
    cards_html = re.sub(
        r'<div style="margin:24px 0 6px.*?</div>\s*',
        '',
        cards_html,
        count=1,
        flags=re.DOTALL,
    )

    return cards_html, table_html


def _append_to_existing_day(html, cards_html, table_html, short_date, day_name):
    """Append new picks to an existing day entry in the blog.

    Returns (updated_html, changes_count).
    """
    existing = _existing_matchups(html, short_date, day_name)
    if not existing:
        print(f"[inject] Date marker found but no existing matchups — treating as fresh")
        return html, 0

    # Extract new cards and filter out ones already in the blog
    new_cards = _extract_pick_cards(cards_html)
    new_table_rows = _extract_table_rows(table_html, short_date)

    cards_to_add = [(mu, card) for mu, card in new_cards if mu not in existing]
    rows_to_add = [(mu, row) for mu, row in new_table_rows if mu not in existing]

    if not cards_to_add:
        print(f"[inject] {short_date} — all {len(new_cards)} picks already in blog, nothing to add")
        return html, 0

    print(f"[inject] {short_date} — {len(cards_to_add)} new picks to append "
          f"({len(existing)} already exist)")

    changes = 0

    # ── Append cards to the existing slate-day-body ──
    # Find the closing </div> of the slate-day-body for this date
    body_pattern = re.compile(
        rf'(<details class="slate-day"[^>]*>\s*<summary>.*?'
        rf'{re.escape(short_date)}.*?</summary>\s*'
        rf'<div class="slate-day-body">)(.*?)(</div>\s*</details>)',
        re.DOTALL,
    )
    body_match = body_pattern.search(html)
    if body_match:
        pre = body_match.group(1)
        body_content = body_match.group(2)
        post = body_match.group(3)

        # Build the new cards HTML
        new_cards_html = "\n".join(card for _, card in cards_to_add)
        updated_body = body_content.rstrip() + "\n" + new_cards_html + "\n"

        html = html[:body_match.start()] + pre + updated_body + post + html[body_match.end():]
        changes += 1
        for mu, _ in cards_to_add:
            print(f"  + Added pick card: {mu}")
    else:
        print(f"  Could not find slate-day-body for {short_date}")

    # ── Append table rows ──
    if rows_to_add:
        # Find the date header row in the table and insert after the last row for that date
        # The date header is like: <!-- MAR 11 — WEDNESDAY -->
        date_header_pattern = re.compile(
            rf'(<!-- {re.escape(short_date)} — [A-Z]+ -->.*?'
            rf'(?:<tr style="border-bottom.*?</tr>\s*)+)',
            re.DOTALL,
        )
        header_match = date_header_pattern.search(html)
        if header_match:
            insert_pos = header_match.end()
            new_rows_html = "\n".join(row for _, row in rows_to_add) + "\n"
            html = html[:insert_pos] + new_rows_html + html[insert_pos:]
            changes += 1
            for mu, _ in rows_to_add:
                print(f"  + Added table row: {mu}")
        else:
            print(f"  Could not find table section for {short_date}")

    # ── Update the summary metadata (pick count + risk) ──
    if changes > 0:
        total_picks = len(existing) + len(cards_to_add)

        # Parse new risk from the cards
        new_risk = 0
        for _, card in cards_to_add:
            risk_m = re.search(r'(\d+) \$PP', card)
            if risk_m:
                new_risk += int(risk_m.group(1))

        # Parse existing risk from the summary
        meta_pattern = re.compile(
            rf'(<span class="slate-day-meta">)(\d+ SPREADS?(?:\s*\+\s*\d+ ML)?)\s*·\s*(\d+) \$PP(</span>)'
        )
        # Find the meta span near our date
        block_pattern = re.compile(
            rf'({re.escape(short_date)}.*?<span class="slate-day-meta">)'
            rf'(.*?·\s*)(\d+)( \$PP</span>)',
            re.DOTALL,
        )
        meta_match = block_pattern.search(html)
        if meta_match:
            old_risk = int(meta_match.group(3))
            new_total_risk = old_risk + new_risk

            # Update pick count text
            type_text = f"{total_picks} SPREADS"
            new_meta = f"{meta_match.group(1)}{type_text} · {new_total_risk}{meta_match.group(4)}"
            html = html[:meta_match.start()] + new_meta + html[meta_match.end():]
            print(f"  Updated summary: {total_picks} picks, {new_total_risk} $PP")

    return html, changes


def inject(snippet_path, blog_path):
    """Inject blog snippet into MORELLOSIMS blog HTML."""
    with open(snippet_path) as f:
        snippet = f.read()

    with open(blog_path) as f:
        html = f.read()

    # Parse metadata from snippet comments
    date_match = re.search(r'Blog snippet for (\d{4}-\d{2}-\d{2})', snippet)
    meta_match = re.search(r'(\d+) picks?, (\d+) \$PP risked', snippet)

    if not date_match:
        print("[inject] Could not find date in snippet")
        return 0

    date_str = date_match.group(1)
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
              "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
    short_date = f"{months[dt.month - 1]} {dt.day}"
    day_name = DAYS[dt.weekday()]
    pick_count = int(meta_match.group(1)) if meta_match else 0
    total_risk = int(meta_match.group(2)) if meta_match else 0

    # Parse snippet into cards and table sections
    cards_html, table_html = _parse_snippet(snippet)

    # ── Check if date already exists in the blog ──
    date_exists = (
        f"{short_date} SLATE" in html
        or f"{short_date} &middot;" in html
        or f"{short_date} · {day_name}" in html
    )

    if date_exists:
        print(f"[inject] {short_date} already exists — checking for new picks to append...")
        html, changes = _append_to_existing_day(
            html, cards_html, table_html, short_date, day_name
        )
        if changes > 0:
            with open(blog_path, "w") as f:
                f.write(html)
            print(f"[inject] Done — appended new picks to existing {short_date} entry")
        else:
            print(f"[inject] No new picks to add for {short_date}")
        return changes

    # ── Fresh injection: date doesn't exist yet ──
    print(f"[inject] Injecting {short_date} · {day_name} slate ({pick_count} picks, {total_risk} $PP)...")

    changes = 0

    # Build the <details class="slate-day"> wrapper
    type_text = f"{pick_count} SPREADS"  # TODO: handle ML/total counts
    slate_entry = f'''                    <details class="slate-day" open>
                        <summary>
                            <div>
                                <span class="slate-day-label">{short_date} · {day_name}</span>
                                <span class="slate-day-meta">{type_text} · {total_risk} $PP</span>
                            </div>
                            <span class="slate-day-record" style="color:#FFD600;">PENDING</span>
                        </summary>
                        <div class="slate-day-body">

{cards_html}

                        </div>
                    </details>

'''

    # Insert pick cards before the first existing <details class="slate-day">
    first_slate = re.search(r'(\s*<details class="slate-day")', html)
    if first_slate:
        pos = first_slate.start()
        html = html[:pos] + "\n" + slate_entry + html[pos:]
        changes += 1
        print(f"  Inserted slate entry before first existing day")
    else:
        # Fallback: insert after the UNIT KEY section
        unit_key = re.search(r'(UNIT KEY:.*?</div>)\s*\n', html)
        if unit_key:
            pos = unit_key.end()
            html = html[:pos] + "\n\n" + slate_entry + html[pos:]
            changes += 1
            print(f"  Inserted slate entry after UNIT KEY")
        else:
            print("  Could not find insertion point for slate entry")

    # Inject table rows
    if table_html:
        tbody_match = re.search(r'(<tbody[^>]*>)\s*\n', html)
        if tbody_match:
            insert_pos = tbody_match.end()
            html = html[:insert_pos] + "\n" + table_html + "\n" + html[insert_pos:]
            changes += 1
            print(f"  Inserted table rows after <tbody>")
        else:
            print("  Could not find <tbody> for table row insertion")

    if changes > 0:
        with open(blog_path, "w") as f:
            f.write(html)
        print(f"[inject] Done — {changes} sections injected")
    else:
        print("[inject] No changes made")

    return changes


def main():
    if len(sys.argv) != 3:
        print("Usage: python inject_blog_entry.py <blog_snippet.html> <blog_html>")
        sys.exit(1)

    snippet_path = sys.argv[1]
    blog_path = sys.argv[2]

    inject(snippet_path, blog_path)


if __name__ == "__main__":
    main()
