#!/usr/bin/env python3
"""
inject_blog_entry.py — Insert a blog_snippet.html into the MORELLOSIMS blog.

Reads blog_snippet.html (generated by generate_blog_entry.py) and injects:
  - Pick cards wrapped in <details class="slate-day"> into the blog
  - Table rows into the picks tracker table

Usage:
  python scripts/inject_blog_entry.py <blog_snippet.html> <morellosims_index.html>
"""

import re
import sys
from datetime import datetime


# Day-of-week abbreviations
DAYS = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]


def inject(snippet_path, blog_path):
    """Inject blog snippet into MORELLOSIMS blog HTML."""
    with open(snippet_path) as f:
        snippet = f.read()

    with open(blog_path) as f:
        html = f.read()

    # Parse metadata from snippet comments
    date_match = re.search(r'Blog snippet for (\d{4}-\d{2}-\d{2})', snippet)
    meta_match = re.search(r'(\d+) picks?, (\d+) \$PP risked', snippet)

    if not date_match:
        print("[inject] Could not find date in snippet")
        return 0

    date_str = date_match.group(1)
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
              "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
    short_date = f"{months[dt.month - 1]} {dt.day}"
    day_name = DAYS[dt.weekday()]
    pick_count = int(meta_match.group(1)) if meta_match else 0
    total_risk = int(meta_match.group(2)) if meta_match else 0

    # Check for duplicates
    if f"{short_date} SLATE" in html or f"{short_date} &middot;" in html or f"{short_date} · {day_name}" in html:
        print(f"[inject] {short_date} already exists in blog — skipping")
        return 0

    print(f"[inject] Injecting {short_date} · {day_name} slate ({pick_count} picks, {total_risk} $PP)...")

    # Split snippet into cards and table rows
    table_marker = "<!-- ═══ TABLE ROWS (insert before </tbody>) ═══ -->"
    cards_marker = "<!-- ═══ PICK CARDS (insert before picks table) ═══ -->"

    cards_html = ""
    table_html = ""

    if table_marker in snippet:
        parts = snippet.split(table_marker)
        cards_section = parts[0]
        table_html = parts[1].strip()
    else:
        cards_section = snippet

    # Extract just the pick card divs (remove comment headers and slate header div)
    cards_html = cards_section.replace(cards_marker, "")
    # Remove the metadata comments
    cards_html = re.sub(r'<!-- Blog snippet for .+? -->\n', '', cards_html)
    cards_html = re.sub(r'<!-- \d+ picks?, \d+ \$PP risked -->\n', '', cards_html)
    cards_html = cards_html.strip()

    # Remove the standalone slate header div (it's part of the snippet but we'll use the details summary)
    cards_html = re.sub(
        r'<div style="margin:24px 0 6px.*?</div>\s*',
        '',
        cards_html,
        count=1,
        flags=re.DOTALL,
    )

    changes = 0

    # ── Build the <details class="slate-day"> wrapper ──
    type_text = f"{pick_count} SPREADS"  # TODO: handle ML/total counts
    slate_entry = f'''                    <details class="slate-day" open>
                        <summary>
                            <div>
                                <span class="slate-day-label">{short_date} · {day_name}</span>
                                <span class="slate-day-meta">{type_text} · {total_risk} $PP</span>
                            </div>
                            <span class="slate-day-record" style="color:#FFD600;">PENDING</span>
                        </summary>
                        <div class="slate-day-body">

{cards_html}

                        </div>
                    </details>

'''

    # ── Insert pick cards before the first existing <details class="slate-day"> ──
    first_slate = re.search(r'(\s*<details class="slate-day")', html)
    if first_slate:
        pos = first_slate.start()
        html = html[:pos] + "\n" + slate_entry + html[pos:]
        changes += 1
        print(f"  Inserted slate entry before first existing day")
    else:
        # Fallback: insert after the UNIT KEY section
        unit_key = re.search(r'(UNIT KEY:.*?</div>)\s*\n', html)
        if unit_key:
            pos = unit_key.end()
            html = html[:pos] + "\n\n" + slate_entry + html[pos:]
            changes += 1
            print(f"  Inserted slate entry after UNIT KEY")
        else:
            print("  Could not find insertion point for slate entry")

    # ── Inject table rows ──
    if table_html:
        tbody_match = re.search(r'(<tbody[^>]*>)\s*\n', html)
        if tbody_match:
            insert_pos = tbody_match.end()
            html = html[:insert_pos] + "\n" + table_html + "\n" + html[insert_pos:]
            changes += 1
            print(f"  Inserted table rows after <tbody>")
        else:
            print("  Could not find <tbody> for table row insertion")

    if changes > 0:
        with open(blog_path, "w") as f:
            f.write(html)
        print(f"[inject] Done — {changes} sections injected")
    else:
        print("[inject] No changes made")

    return changes


def main():
    if len(sys.argv) != 3:
        print("Usage: python inject_blog_entry.py <blog_snippet.html> <blog_html>")
        sys.exit(1)

    snippet_path = sys.argv[1]
    blog_path = sys.argv[2]

    inject(snippet_path, blog_path)


if __name__ == "__main__":
    main()
